### ISSUE TITLE
Display icons for gear

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [Maselkov/Maselkov-Cogs#12]
I'm currently trying to get the icons for character gear displayed, but the bot doesn't embed the icon preview. Only the full url to the icon via api is displayed. Any idea to fix this?

**Comment by n1tr0-5urf3r** [comment]
It looks like the .png can't be displayed inline with the text
Maybe it is possible to create a temporary server emoji out of the file, add it to msg and remove it afterwards?

**Comment by Maselkov** [comment]
I'm not sure if individual embed fields can display icons - refer to [this](https://cdn.discordapp.com/attachments/84319995256905728/252292324967710721/embed.png). But it's worth looking into.

**Comment by Maselkov** [comment]
The emoji idea is clever. Discord.py does have an endpoint for adding custom emojis.

**Comment by n1tr0-5urf3r** [comment]
I'm not yet that much into python/Discord API, but it seems like you can't create Emojis from a URL. So we have to download it temporarily first, create emoji, and delete both? 
Also Emojis seem to stay in chat history, even if you delete them from the server.

**Comment by Maselkov** [comment]
Yes, downloading temporarily is the way in this case.

As for the second point, that's great to hear - it was my biggest worry for this solution.
