### ISSUE TITLE
Add language parameter

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [Maselkov/Maselkov-Cogs#27]
Maybe implement a configure option to set language and store it in json? 
Can be easily appended with ?lang=de for example

**Comment by Maselkov** [comment]
Some endpoints don't seem to support language.

This seems doable, could be a per server option for admins. Or maybe per user if user has key?

**Comment by n1tr0-5urf3r** [comment]
I think per server for admins would be enough. Maybe only for the items endpoint

**Comment by Maselkov** [comment]
Wouldn't it be a bit out of place without translated embed titles/field names?

**Comment by n1tr0-5urf3r** [comment]
Maybe, but one of my guildies said that he doesn't know the item names in english needed for our treasury and i guess everyone could translate at least the titles
