### ISSUE TITLE
[GW2] TP Listing Problem

### ISSUE THREAD

**Issue by sfalexw** [Maselkov/Maselkov-Cogs#32]
Recently notice a problem under the tp listing function. Redbot will throw an `IndexError` when you mass buying/selling the same item for more than a stack or at different price.

```
Exception in command 'tp current'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/red-discordbot/cogs/guildwars2.py", line 1367, in current
    item_name = itemlist[counter]["name"]
IndexError: list index out of range
```

Probably due to the fact that items API and commerce/listings API will not reply duplicated information from the same item id. See example [here](https://api.guildwars2.com/v2/items?ids=21263,21263) and [here](https://api.guildwars2.com/v2/commerce/listings?ids=21263,21263).

**Comment by sfalexw** [comment]
I am currently working on a fix, and I should be able to finish it today.

**Comment by Maselkov** [comment]
#33
