### ISSUE TITLE
Add WvW server info

### ISSUE THREAD

**Issue by NayNayz** [Maselkov/Maselkov-Cogs#4]
:)

**Comment by Maselkov** [comment]
Could someone explain me how are points per tick calculated? I never play WvW

**Comment by NayNayz** [comment]
To calculate points per tick the game sums up all the objectives that the server owns across 4 maps (eternal battlegrounds, desert borderlands and 2 alpine borderlands). Each objective gives a different amount of points per tick based on what type of objective it is and how upgraded it is.

**Comment by Maselkov** [comment]
Much appreciated

**Comment by Maselkov** [comment]
What are values you'd like to see? Currently I have "score" (I think it's the warscore), victory points and points per tick

**Comment by NayNayz** [comment]
Those are perfect, can't think of anything else i'd like to see.

**Comment by Maselkov** [comment]
[p]wvw has been added, thank you for the suggestion. Feel free to request improvements
