### ISSUE TITLE
[p]Bosses is broken with Wing 5

### ISSUE THREAD

**Issue by DammitStella** [Maselkov/Maselkov-Cogs#41]
> Exception in command 'bosses'
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/home/pi/red/cogs/guildwars2.py", line 1044, in bosses
>     key=lambda val: self.gamedata["bosses"][val]["order"])
>   File "/home/pi/red/cogs/guildwars2.py", line 1044, in <lambda>
>     key=lambda val: self.gamedata["bosses"][val]["order"])
> KeyError: 'statues_of_grenth'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 374, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "lib/discord/ext/commands/core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'statues_of_grenth'
> 

Steps to reproduce:
Have done Statues
use [p]bosses
use [p]traceback

**Comment by Maselkov** [comment]
GW2 module here is no longer being supported, see https://github.com/Maselkov/GW2Bot

If you're still using it, feel free to open a PR and I'll review it anyway.
