### ISSUE TITLE
[Lewd] cog not working

### ISSUE THREAD

**Issue by Zalatis** [Maselkov/Maselkov-Cogs#43]
Lewd cog actually not working 

Expecting value: line 1 column 1 (char 0) for e621
and 
BAD REQUEST (status code: 400) for rule34

**Comment by Maselkov** [comment]
Maybe I'll fix it at some point, but don't know. You can find an updated version [here](https://github.com/iShauny/Botter/blob/master/cogs/lewd.py), although this is for Toothy, not red.

**Comment by Zalatis** [comment]
Ok thanks ;)
