### ISSUE TITLE
Enhancement: Bank info

### ISSUE THREAD

**Issue by StephanMa** [Maselkov/Maselkov-Cogs#5]
At least... great work! Thank you!

for some further development i would like to have an overview of the bank account... including gold and finances ^^

**Comment by Maselkov** [comment]
What would you like to see in such overview? How much of currency you have? Something else you had in mind?

**Comment by StephanMa** [comment]
Well i think, it will be very problematic to display the entire bank stuff.
But at least your current currency, maybe carma, gems and stuff like this?

**Comment by Maselkov** [comment]
Wallet should be simple enough then

**Comment by Maselkov** [comment]
[P]wallet has been added, thank you for the request!
