### ISSUE TITLE
[GW2] Add searching for item on account

### ISSUE THREAD

**Issue by Maselkov** [Maselkov/Maselkov-Cogs#7]
Like gw2efficiency account search feature

**Comment by Maselkov** [comment]
So I think this would require some sort of backend database with all the items, else it would be pathetically slow. But I'm not really sure how to go about doing that. A database would also solve the issue for calculating AP

Help is appreciated

**Comment by Maselkov** [comment]
With API rate limits coming in, I think this will be the next major feature to be worked on. I'm currently planning to use MongoDB.

**Comment by StephanMa** [comment]
I would suggest to synch all items to your db. That will reduce the amount of API-Calls when checking gear.  Next step is to synch the items from a account->char and get the infos from the DB......

something like this

**Comment by Maselkov** [comment]
Added in mongo branch
